import { cn } from '@/lib/utils'
import './globals.css'
import type { Metadata } from 'next' 
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'
import React from 'react'
import { ThemeProvider } from "@/components/theme-provider"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Compliance Suit',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode // Type definition for children prop
}) {
  return (
    <html lang='en' className='light'>
      <body
        className={cn(
          'min-h-screen font-sans antialiased grainy', // Tailwind CSS classes
          inter.className // Inter font class name
        )}>
         <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >

        {children}
        </ThemeProvider>
      </body>
    </html>
  )
}